### PR TITLE
Add Sublime Text 3 theme

### PR DESCRIPTION
**Pull request by cheshire137**
Hi! I generated this version of the Soft Era theme using https://tmtheme-editor.herokuapp.com/, based on variables in https://github.com/soft-aesthetic/soft-era-atom-syntax/blob/7b0d6220592c5631eeb5853634fabe2d1a59c5a3/styles/colors.less and https://github.com/soft-aesthetic/soft-era-atom-syntax/blob/7b0d6220592c5631eeb5853634fabe2d1a59c5a3/styles/syntax-variables.less. Here's what it looks like with a Ruby file in Sublime Text 3:

image

/cc @animalphase

### CODE REVIEW

**Comment by lovemecomputer** [comment]
🌸
@cheshire137 awesome work!!!!! this looks great!! thank you for submitting this pull request~~

bitmoji

i'm noticing one issue, that number literals should be the same '#414141' value as strings. at some point later on i am going to do a pass over all the theme ports, tweaking contrast etc across environments, and i'll save any value tweaks and corrections until then :)

**Comment by lovemecomputer** [comment]
btw @cheshire137 ~ i wanna tweet about sublime text support, is it okay if i @ you in the tweet?

**Comment by cheshire137** [comment]
> later on i am going to do a pass over all the theme ports, tweaking contrast etc

Sounds good to me. 👍 

> i wanna tweet about sublime text support, is it okay if i @ you in the tweet?

Sure! I'm @cheshire137 on Twitter, too.

**Comment by lovemecomputer** [comment]
@cheshire137 👍🏻👍🏻👍🏻👍🏻

**Pull request merged**
